In [1]:
import pandas as pd
import numpy as np


c:\Users\Shaheryar\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
df = pd.read_csv('customer.csv')
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [4]:
df = df.iloc[:, 2:] 
#age is already numeric
#and gender is nominal data
#removing age and gender to apply ordinal encoder on review and education
#label encoder on purchased - y
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [5]:
X = df.iloc[:, 0:2]
X

review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [6]:
y = df.iloc[:, -1]
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [8]:
X_train

review education
17     Poor        UG
39     Poor        PG
5   Average    School
41     Good        PG
14     Poor        PG
6      Good    School
43     Poor        PG
32  Average        UG
15     Poor        UG
44  Average        UG
40     Good    School
28     Poor    School
18     Good    School
8   Average        UG
30  Average        UG
2      Good        PG
45     Poor        PG
48     Good        UG
35     Poor    School
38     Good    School
49     Good        UG
27     Poor        PG
13  Average    School
7      Poor    School
1      Poor        UG
12     Poor    School
11     Good        UG
16     Poor        UG
33     Good        PG
20  Average    School
19     Poor        PG
4   Average        UG
36     Good        UG
42     Good        PG
0   Average    School
29  Average        UG
24  Average        PG
31     Poor    School
25     Good    School
23     Good    School

In [9]:
from sklearn.preprocessing import OrdinalEncoder

#get ordinal encoder and also define categories
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG", "PG"]])

#fit ordinal encoder
oe.fit(X_train)


OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)
X_train

array([[0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.]])

In [11]:
X_test

array([[0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.]])

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
le.fit(y_train) #use label encoder on y - purchased

LabelEncoder()

In [14]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [15]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0])

In [16]:
y_test

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 0])